Ajuste de archivos
jchernandezUA/tswdc-project pull request #35
Opened 2024-05-07 23:02 UTC by miguelenruiz1

2024-05-08 01:47 UTC, jchernandezUA requested changes

2024-05-08 17:54 UTC, miguelenruiz1 commented on kraken/features/003_eliminar_post.feature
en le primer archivo 001 esta la creacion del post New Post Title que es el que se elimina cuando llega a este paso

2024-05-09 04:13 UTC, jchernandezUA commented on kraken/features/003_eliminar_post.feature
pero tu prueba debería crear un post y luego eliminarlo, suponiendo que tu test 1 no pasa o no corre antes que este

2024-05-09 04:17 UTC, jchernandezUA commented on kraken/features/003_eliminar_post.feature
✖ Then I should see that the post with title "New Post Title" is deleted # features/web/step_definitions/003_eliminar_post.js:67
       Attachment (image/png)
       Error: Post with title "New Post Title" was not deleted
           at KrakenWorld.<anonymous> (/Users/rojo/MISO/Pruebas automatizadas/tswdc-project/kraken/features/web/step_definitions/003_eliminar_post.js:75:15)
           at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
   ✔ After # features/web/support/hooks.js:15

1 scenario (1 failed)
7 steps (1 failed, 6 passed)

2024-05-09 18:44 UTC, miguelenruiz1 commented on kraken/features/003_eliminar_post.feature
corregido: se crea un post que se pasa por parametro desde el feature eliminar post

2024-05-09 20:42 UTC, jchernandezUA approved these changes
Listo todas corrieron 👍

2024-05-09 20:43 UTC, merged